CREATE TABLE konwersje (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kwota DECIMAL(10,2) NOT NULL,
    waluta_z VARCHAR(3) NOT NULL,
    waluta_do VARCHAR(3) NOT NULL,
    wynik DECIMAL(10,5) NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);